### PR TITLE
Nothing

### PR DESCRIPTION
**Pull request by fhamersley**
This is the binary file of the original vanilla driver from Aldebaran.
Requested to be accessible by the team without flashing a Nao.

### CODE REVIEW

**Comment by pzrq** [comment]
@fhamersley As I'm not seeing a new or updated README.md or any details on this PR:

- Where did the source code from?
- What if any modifications did you make?
- What if any instructions did you follow to compile the binary?
- What platform or tools was it compiled on? What hardware (e.g. Nao V5? Host names? Specific camera model numbers or build numbers as we've seen problems with Loki for instance) has it been tested and confirmed to work on?

**Comment by pzrq** [comment]
Sorry I just read in a bit more detail, if it's from Aldebaran, what CTC or release was it part of?

**Comment by fhamersley** [comment]
Its the same camera driver that comes with a nao. One way to get it is to flash a nao. This was purely to make it more efficient to roll back the driver when running an old branch of runswift. Required by Ethan and co to collect data on the 2016 ball detector for the paper being written.

**Comment by fhamersley** [comment]
Closing cause probably a pretty bad idea.

**Comment by pzrq** [comment]
As stated:

> This is the binary file of the original vanilla driver from Aldebaran.

Discussed out of band that it's really [hard to delete things from GitHub once they have been pull requested](https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github). I'm not personally sure exactly where this file came from, and in practice, the team is no longer using it, and if anything may have even less use as the Nao V6 and updated drivers, OS and toolchains become available in the hopefully not too distant future.

More specifically, it is my understanding that the team is actually using the [Nao Devils camera driver](https://github.com/NaoDevils/NaoKernel#information-about-the-camera-driver) introduced in https://github.com/UNSWComputing/rUNSWift-assets/commit/bec3ecc1c849ee19be3d5ab571b4e76f9c6c3e02

There is an internal rUNSWift GitHub issue to document it more fully than I can here.

On behalf of the team, I wish to extend my sincere apologies for wasting anyone's time.

**Pull request closed without merging**
